### ISSUE TITLE
Care about your card info in your code

### ISSUE THREAD

**Issue by zz920** [ranaivmi/SupremeBot#1]
Hey, I just search for a supreme bot, and happened to find some credit card info in your code. I don't know whether it's real, although it looks real. So I just post this issue to remind you to care about it. Maybe there are not much stars on this project, but there are still many people like me scanning codes for some unknown purposes. Anyway, care about it : )

**Comment by StevenChicago** [comment]
Still up there

**Comment by ranaivmi** [comment]
The information about the credit card are wrong even if it looks real. Thanks for your post, I'll take care about it : )
